services:
  db:
    container_name: database
    image: postgres:15-alpine
    hostname: database
    env_file: .env
    ports:
      - '9999:5432'
    volumes:
      - ./migrations/smartfood.sql:/docker-entrypoint-initdb.d/smartfood.sql
      # - ./migrations/seed.sql:/docker-entrypoint-initdb.d/seed.sql
